const colors = {
  light: {
    text: "#0D1B2A",
    tint: "#FF6B00",
    background: "#FFFFFF",
    foreground: "#0D1B2A",
    card: "#FFFFFF",
    cardForeground: "#0D1B2A",
    primary: "#0D1B2A",
    primaryForeground: "#FFFFFF",
    secondary: "#F5F6FA",
    secondaryForeground: "#0D1B2A",
    muted: "#F5F6FA",
    mutedForeground: "#6B7280",
    accent: "#FF6B00",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#E5E7EB",
    surface: "#F5F6FA",
    navyDark: "#0A1628",
    navyMid: "#162035",
    orangeLight: "#FF8C42",
    orangeDark: "#E55A00",
    gold: "#FFD700",
    silver: "#C0C0C0",
    bronze: "#CD7F32",
    emeraldColor: "#50C878",
    sapphireColor: "#0F52BA",
    rubyColor: "#9B111E",
    success: "#10B981",
    warning: "#F59E0B",
  },
  radius: 12,
};

export default colors;
